PUT http://localhost:3001/api/blogs/61e1e76d915dd6fc7203088b
Content-Type: application/json

{
	"title": "João Pedro blog",
	"author": "Joao Pedro",
	"url": "https://jocorrei.github.io/My-portifolio/",
	"likes": 1000
}